export { ChevronLeft } from './chevronLeft'
export { ChevronRight } from './chevronRight'
export { ArrowLeft } from './arrowLeft'
export { ArrowRight } from './arrowRight'
export { Trashcan } from './trashcan'
export { Favorites } from './favorites'
export {ActiveItemIcon} from './activeItem'
export { StoresIcon } from './storesIcon'
export { Icon } from './icon'